// Generated API types and client from server/api/openapi.yaml
//
// This module is auto-generated by the swift-openapi-generator build plugin.
// Do not hand-edit the generated Types.swift or Client.swift files.
//
// To regenerate: the build plugin runs automatically on each build.
// The source of truth is server/api/openapi.yaml - copy it here when the spec changes:
//   cp server/api/openapi.yaml app/Sources/ScreenSpaceAPI/openapi.yaml

@_exported import OpenAPIRuntime
@_exported import OpenAPIURLSession
