// Generated API types and client from the OpenAPI spec.
//
// This module is auto-generated by the swift-openapi-generator build plugin.
// Do not hand-edit the generated Types.swift or Client.swift files.
//
// The openapi.yaml in this directory is a symlink to server/api/openapi.yaml,
// which is the single source of truth for the API contract.
// The build plugin regenerates automatically on each build.

@_exported import OpenAPIRuntime
@_exported import OpenAPIURLSession
